Remove old <src> and <testsrc> elements so it finds my tests. Fails.
Fails with NoClassDefFoundError: javax/validation/ParameterNameProvider

despite liberally following advice on project configuration at
http://docs.jboss.org/hibernate/validator/5.0/reference/en-US/html_single/